---
title: "Classroom Notes Week 3"
author: "Reginald Carey"
date: "March 14, 2015"
output: html_document
---

##Hierarchical Clustering - example

```{r,cache=TRUE}
set.seed(1234)
par(mar = c(0,0,0,0))
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1,2,1), each = 4), sd = 0.2)
plot(x,y,col="blue",pch=19,cex=2)
text(x+0.05, y+0.05, labels = as.character(1:12))
```

```{r,cache=TRUE}
dataFrame = data.frame(x=x,y=y)
dist(dataFrame)
```

```{r,cache=TRUE}
distxy <- dist(dataFrame)
hClustering = hclust(distxy)
plot(hClustering)
```

Heatmap

```{r,cache=TRUE}
dataFrame = data.frame(x=x,y=y)
set.seed(143)
dataMatrix <- as.matrix(dataFrame)[sample(1:12),]
heatmap(dataMatrix)
```

K-Means Clustering

```{r,cache=TRUE}
set.seed(1234)
par(mar = c(0,0,0,0))
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1,2,1), each = 4), sd = 0.2)
plot(x,y,col="blue",pch=19,cex=2)
text(x+0.05, y+0.05, labels = as.character(1:12))
```

```{r,cache=FALSE}
dataFrame = data.frame(x=x,y=y)
kmeansObj <- kmeans(dataFrame, centers = 4)
names(kmeansObj)
```

```{r,cache=FALSE}
kmeansObj$cluster
```


```{r,cache=FALSE}
par(mar = rep(0.2, 4))
plot(x,y, col = kmeansObj$cluster, pch = 19, cex = 2)
points(kmeansObj$centers, col = 1:4, pch = 3, cex = 3, lwd = 3)
```









